### ISSUE TITLE
Responsive Page

### ISSUE THREAD

**Issue by H-Maurya** [H-Maurya/Hacktoberfest-x-DetectiveConan#6]
The web page is not responsive; neither are the images present in it. Alter the code such that the page becomes responsive.

**Comment by 17Moons** [comment]
i can do that ...brb

**Comment by lognoroy** [comment]
I can do it. please give me a chance.

**Comment by H-Maurya** [comment]
This Repository is excluded from Hacktoberfest. If you want to contribute, you are welcome.
